import { useEffect, useRef, useState } from "react";
import CardSection from "../CardSection";
import Modal from "../Modal";
import { formatDateTime } from "../utils";

function CopyIcon({ copied }) {
  if (copied) {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M5 13l4 4L19 7" />
      </svg>
    );
  }

  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <rect x="9" y="9" width="10" height="10" rx="2" />
      <path d="M6 15H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

export default function KeysView({
  apiKeys,
  isBusy,
  busy,
  loadApiKeys,
  openCreateKeyDialog,
  revokeApiKey,
  navigateConsoleView,
  createKeyOpen,
  closeCreateKeyDialog,
  createManagedApiKey,
  newKeyName,
  setNewKeyName,
  newKeyExpiresAt,
  setNewKeyExpiresAt,
  newApiKey,
  keyDialogError,
  formatCompactNumber,
  formatMoneyCompact,
}) {
  const [baseUrlCopied, setBaseUrlCopied] = useState(false);
  const baseUrlCopyTimerRef = useRef(null);
  const openAiBaseUrl = typeof window === "undefined" ? "/v1" : `${window.location.origin}/v1`;

  useEffect(() => {
    return () => {
      if (baseUrlCopyTimerRef.current) {
        window.clearTimeout(baseUrlCopyTimerRef.current);
      }
    };
  }, []);

  async function copyOpenAiBaseUrl() {
    try {
      await navigator.clipboard.writeText(openAiBaseUrl);
      setBaseUrlCopied(true);
      if (baseUrlCopyTimerRef.current) {
        window.clearTimeout(baseUrlCopyTimerRef.current);
      }
      baseUrlCopyTimerRef.current = window.setTimeout(() => {
        setBaseUrlCopied(false);
        baseUrlCopyTimerRef.current = null;
      }, 1400);
    } catch (error) {
      console.error("Failed to copy OpenAI base URL", error);
    }
  }

  return (
    <>
      <CardSection title="Base URL">
        <p className="muted">Use this as the OpenAI SDK baseURL.</p>
        <div className="approval-link-box">
          <div className="approval-link-header">
            <span>OpenAI base URL</span>
            <button
              className={`approval-copy-button${baseUrlCopied ? " copied" : ""}`}
              type="button"
              onClick={copyOpenAiBaseUrl}
              aria-label={baseUrlCopied ? "Base URL copied" : "Copy base URL"}
              title={baseUrlCopied ? "Copied" : "Copy base URL"}
            >
              <CopyIcon copied={baseUrlCopied} />
            </button>
          </div>
          <code>{openAiBaseUrl}</code>
        </div>
      </CardSection>

      <CardSection
        title="API Keys"
        actions={
          <div className="row">
            <button className="primary" disabled={isBusy} onClick={loadApiKeys}>Refresh</button>
            <button disabled={isBusy} className="primary" onClick={openCreateKeyDialog}>Create key</button>
          </div>
        }
      >
        <p className="muted">Manage keys for OpenAI-compatible API access. Keys are generated by the Worker and shown once.</p>

        {apiKeys.length ? (
          <div className="data-list">
            {apiKeys.map((item) => (
              <div className="data-row" key={item.id}>
                <div>
                  <strong>{item.name || `${item.prefix}_...${item.key_suffix}`}</strong>
                  <span>
                    {item.prefix}_...{item.key_suffix} · {item.status}
                    {item.expires_at ? ` · expires ${formatDateTime(item.expires_at)}` : ""}
                  </span>
                  {typeof item.calls === "number" && (
                    <div className="usage-stats">
                      <div className="stat-box">
                        <div className="num">{item.calls.toLocaleString()}</div>
                        <div className="label">Calls</div>
                      </div>
                      <div className="stat-box">
                        <div className="num">{formatCompactNumber(item.total_tokens || 0)}</div>
                        <div className="label">Tokens</div>
                      </div>
                      <div className="stat-box">
                        <div className="num">{formatMoneyCompact(item.total_cost || 0)}</div>
                        <div className="label">Cost</div>
                      </div>
                      <div className="stat-box">
                        <div className="num">{item.calls > 0 ? Math.round(((item.calls - (item.errors || 0)) / item.calls) * 100) : 0}%</div>
                        <div className="label">Success</div>
                      </div>
                    </div>
                  )}
                </div>
                <button
                  className="secondary danger"
                  disabled={isBusy || item.status !== "active"}
                  onClick={() => revokeApiKey(item.id)}
                >
                  Revoke
                </button>
              </div>
            ))}
          </div>
        ) : (
          <div className="empty-state">
            <strong>No keys</strong>
            <p>Create a deposit first. The Worker will generate the initial API key after settlement.</p>
            <button type="button" className="primary" onClick={() => navigateConsoleView("recharge")}>Go to Recharge</button>
          </div>
        )}
      </CardSection>

      {createKeyOpen && (
        <Modal
          open={createKeyOpen}
          onClose={closeCreateKeyDialog}
          title="Create API Key"
          subtitle="The generated key is shown once."
          titleId="create-key-title"
        >
          <form onSubmit={createManagedApiKey}>
            <div className="grid single">
              <label>
                <span>Name</span>
                <input value={newKeyName} placeholder="Auto-generated if empty" onChange={(event) => setNewKeyName(event.target.value)} />
              </label>
              <label>
                <span>Expires</span>
                <input type="datetime-local" value={newKeyExpiresAt} onChange={(event) => setNewKeyExpiresAt(event.target.value)} />
              </label>
            </div>
            {keyDialogError && <p className="form-error">{keyDialogError}</p>}
            {newApiKey && (
              <div className="generated-key">
                <span>New key</span>
                <code>{newApiKey}</code>
              </div>
            )}
            <div className="modal-actions">
              <button type="button" className="secondary" onClick={closeCreateKeyDialog}>Close</button>
              <button type="submit" className="primary" disabled={busy === "createApiKey"}>
                {busy === "createApiKey" ? "Creating..." : "Create key"}
              </button>
            </div>
          </form>
        </Modal>
      )}
    </>
  );
}
